#!/bin/bash

set -ex

load() {
  if [ -d app ]; then
    return
  fi
  flutter create app
  cd app
  git init
  git add -A
  git commit -m "app"
  git apply ../app.patch
  git add -A
  git commit -m "patch"
}

save() {
  if [ ! -d app ]; then
    return
  fi
  (
    cd app
    git reset --soft "$(git log --format="%H" --reverse | head -n 1)"
    git add -A
    git diff --staged > ../app.patch
  )
}

clean() {
  rm -rf app
}

build() {
  rm -rf build
  mkdir -p build
  (
    cd app
    flutter build apk
    cp build/app/outputs/flutter-apk/app-release.apk ../build/android.apk
    flutter build ios --release --no-codesign
    cp build/ios/iphoneos/Runner.app ../build/ios.app
  )
}

case "$1" in
  "load" ) load ;;
  "save" ) save ;;
  "clean" ) clean ;;
  "build" ) build ;;
esac
