name: API (Word)

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt
        working-directory: ./api
      - run: python word.py
        working-directory: ./api
      - uses: peaceiris/actions-gh-pages@v3
        with:
          publish_branch: api
          publish_dir: ./public
