name: API (Word)

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 * * * *"

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - run: pip install -r requirements.txt
        working-directory: ./api
      - run: python word.py
        working-directory: ./api
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          branch: api
          file_pattern: ./public
