name: Flutter

on:
  push:
    branches:
      - main

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12"
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
      - run: flutter build apk
  ios:
    name: iOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
      - run: flutter pub get
      - run: flutter build ios --release --no-codesign
      - run: out=$PWD/app-release.ipa; cd build/ios/iphoneos/Runner.app; zip -r $out .
  web:
    name: Web
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: subosito/flutter-action@v1
        with:
          channel: beta
      - run: flutter pub get
      - run: flutter config --enable-web
      - run: sed -i 's,\(<base href="\)/\(">\),\1/trendkiwami/\2,g' web/index.html
      - run: flutter build web
      - uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/web
