name: Flutter App

on: [create]

jobs:
  build:
    name: Build
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
      - name: Get Packages
        run: flutter pub get
      - name: Build an Android App
        run: flutter build apk
      - name: Build an iPhone App
        run: flutter build ios --release --no-codesign
      - name: Create IPA
        run: path=$PWD/app.ipa; cd build/ios/iphoneos/Runner.app; zip -r $path .
      - uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            build/app/outputs/flutter-apk/app-release.apk
            app.ipa
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
